/*
* English pronoun list
* https://www.ef.edu/english-resources/english-grammar/pronouns/
*
*/

import PronounDictionary from '../../models/dictionaries/pronoun.dictionary';

const subjectPronounList = [
    {
        pronoun: 'I',
        referent: 'animate',
        gender: 'neuter',
        person: 1,
        quantity: 'singular',
        type: 'subject',
    },
    {
        pronoun: 'you',
        referent: 'animate',
        gender: 'neuter',
        person: 2,
        quantity: 'singular',
        type: 'subject',
    },
    {
        pronoun: 'he',
        referent: 'animate',
        gender: 'masculine',
        person: 3,
        quantity: 'singular',
        type: 'subject',
    },
    {
        pronoun: 'she',
        referent: 'animate',
        gender: 'feminine',
        person: 3,
        quantity: 'singular',
        type: 'subject',
    },
    {
        pronoun: 'it',
        referent: 'inanimate',
        gender: 'neuter',
        person: 3,
        quantity: 'singular',
        type: 'subject',
    },
    {
        pronoun: 'we',
        referent: 'animate',
        gender: 'neuter',
        person: 1,
        quantity: 'plural',
        type: 'subject',
    },
    {
        pronoun: 'you',
        referent: 'animate',
        gender: 'neuter',
        person: 2,
        quantity: 'plural',
        type: 'subject',
    },
    {
        pronoun: 'y\'all',
        referent: 'animate',
        gender: 'neuter',
        person: 2,
        quantity: 'plural',
        type: 'subject',
    },
    {
        pronoun: 'yous',
        referent: 'animate',
        gender: 'neuter',
        person: 2,
        quantity: 'plural',
        type: 'subject',
    },
    {
        pronoun: 'they',
        referent: 'animate',
        gender: 'neuter',
        person: 3,
        quantity: 'plural',
        type: 'subject',
    }];

const objectPronounList = [
    {
        pronoun: 'me',
        referent: 'animate',
        gender: 'neuter',
        person: 1,
        quantity: 'singular',
        type: 'object',
    },
    {
        pronoun: 'you',
        referent: 'animate',
        gender: 'neuter',
        person: 2,
        quantity: 'singular',
        type: 'object',
    },
    {
        pronoun: 'him',
        referent: 'animate',
        gender: 'masculine',
        person: 3,
        quantity: 'singular',
        type: 'object',
    },
    {
        pronoun: 'her',
        referent: 'animate',
        gender: 'feminine',
        person: 3,
        quantity: 'singular',
        type: 'object',
    },
    {
        pronoun: 'it',
        referent: 'inanimate',
        gender: 'neuter',
        person: 3,
        quantity: 'singular',
        type: 'object',
    },
    {
        pronoun: 'us',
        referent: 'animate',
        gender: 'neuter',
        person: 1,
        quantity: 'plural',
        type: 'object',
    },
    {
        pronoun: 'you',
        referent: 'animate',
        gender: 'neuter',
        person: 2,
        quantity: 'plural',
        type: 'object',
    },
    {
        pronoun: 'y\'all',
        referent: 'animate',
        gender: 'neuter',
        person: 2,
        quantity: 'plural',
        type: 'object',
    },
    {
        pronoun: 'yous',
        referent: 'animate',
        gender: 'neuter',
        person: 2,
        quantity: 'plural',
        type: 'object',
    },
    {
        pronoun: 'them',
        referent: 'animate',
        gender: 'neuter',
        person: 3,
        quantity: 'plural',
        type: 'object',
    }];

const determinerPronounList = [
    {
        pronoun: 'my',
        referent: 'animate',
        gender: 'neuter',
        person: 1,
        quantity: 'singular',
        type: 'determiner',
    },
    {
        pronoun: 'your',
        referent: 'animate',
        gender: 'neuter',
        person: 2,
        quantity: 'singular',
        type: 'determiner',
    },
    {
        pronoun: 'his',
        referent: 'animate',
        gender: 'masculine',
        person: 3,
        quantity: 'singular',
        type: 'determiner',
    },
    {
        pronoun: 'her',
        referent: 'animate',
        gender: 'feminine',
        person: 3,
        quantity: 'singular',
        type: 'determiner',
    },
    {
        pronoun: 'its',
        referent: 'inanimate',
        gender: 'neuter',
        person: 3,
        quantity: 'singular',
        type: 'determiner',
    },
    {
        pronoun: 'our',
        referent: 'animate',
        gender: 'neuter',
        person: 1,
        quantity: 'plural',
        type: 'determiner',
    },
    {
        pronoun: 'their',
        referent: 'animate',
        gender: 'neuter',
        person: 3,
        quantity: 'plural',
        type: 'determiner',
    }];

const possessivePronounList = [
    {
        pronoun: 'mine',
        referent: 'animate',
        gender: 'neuter',
        person: 1,
        quantity: 'singular',
        type: 'possessive',
    },
    {
        pronoun: 'yours',
        referent: 'animate',
        gender: 'neuter',
        person: 2,
        quantity: 'singular',
        type: 'possessive',
    },
    {
        pronoun: 'his',
        referent: 'animate',
        gender: 'masculine',
        person: 3,
        quantity: 'singular',
        type: 'possessive',
    },
    {
        pronoun: 'hers',
        referent: 'animate',
        gender: 'feminine',
        person: 3,
        quantity: 'singular',
        type: 'possessive',
    },
    {
        pronoun: 'its',
        referent: 'inanimate',
        gender: 'neuter',
        person: 3,
        quantity: 'singular',
        type: 'possessive',
    },
    {
        pronoun: 'ours',
        referent: 'animate',
        gender: 'neuter',
        person: 1,
        quantity: 'plural',
        type: 'possessive',
    },
    {
        pronoun: 'y\'all\'s',
        referent: 'animate',
        gender: 'neuter',
        person: 2,
        quantity: 'plural',
        type: 'possessive',
    },
    {
        pronoun: 'theirs',
        referent: 'animate',
        gender: 'neuter',
        person: 3,
        quantity: 'plural',
        type: 'possessive',
    }];

const reflexivePronounList = [
    {
        pronoun: 'myself',
        referent: 'animate',
        gender: 'neuter',
        person: 1,
        quantity: 'singular',
        type: 'reflexive',
    },
    {
        pronoun: 'yourself',
        referent: 'animate',
        gender: 'neuter',
        person: 2,
        quantity: 'singular',
        type: 'reflexive',
    },
    {
        pronoun: 'himself',
        referent: 'animate',
        gender: 'masculine',
        person: 3,
        quantity: 'singular',
        type: 'reflexive',
    },
    {
        pronoun: 'herself',
        referent: 'animate',
        gender: 'feminine',
        person: 3,
        quantity: 'singular',
        type: 'reflexive',
    },
    {
        pronoun: 'itself',
        referent: 'inanimate',
        gender: 'neuter',
        person: 3,
        quantity: 'singular',
        type: 'reflexive',
    },
    {
        pronoun: 'ourselves',
        referent: 'animate',
        gender: 'neuter',
        person: 1,
        quantity: 'plural',
        type: 'reflexive',
    },
    {
        pronoun: 'themselves',
        referent: 'animate',
        gender: 'neuter',
        person: 3,
        quantity: 'plural',
        type: 'reflexive',
    }];

export default new PronounDictionary([
    ...subjectPronounList,
    ...objectPronounList,
    ...determinerPronounList,
    ...possessivePronounList,
    ...reflexivePronounList], 'En');
